OgrenciMvc/Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OgrenciMvc.Database;
using OgrenciMvc.Models;

namespace OgrenciMvc.Controllers
{
    
    public class OgrenciController : Controller
    {
        private readonly DatabaseContext _context;

        public OgrenciController(DatabaseContext context)
        {
            _context = context;
        }

        [AllowAnonymous]
        // GET: Ogrenci
        public async Task<IActionResult> Index()
        {
            var databaseContext = _context.Ogrenciler.Include(o => o.Bolum);
            return View(await databaseContext.ToListAsync());
        }

        // GET: Ogrenci/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ogrenci = await _context.Ogrenciler
                .Include(o => o.Bolum)
                .FirstOrDefaultAsync(m => m.OgrenciId == id);
            if (ogrenci == null)
            {
                return NotFound();
            }

            return View(ogrenci);
        }

        // GET: Ogrenci/Create
        public IActionResult Create()
        {
            ViewData["BolumId"] = new SelectList(_context.Bolumler, "BolumId", "BolumId");
            return View();
        }

        // POST: Ogrenci/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OgrenciId,Adi,SoyAdi,Email,Sifre,Token,BolumId")] Ogrenci ogrenci)
        {
            if (ModelState.IsValid)
            {
                _context.Add(ogrenci);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["BolumId"] = new SelectList(_context.Bolumler, "BolumId", "BolumId", ogrenci.BolumId);
            return View(ogrenci);
        }

        // GET: Ogrenci/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ogrenci = await _context.Ogrenciler.FindAsync(id);
            if (ogrenci == null)
            {
                return NotFound();
            }
            ViewData["BolumId"] = new SelectList(_context.Bolumler, "BolumId", "BolumId", ogrenci.BolumId);
            return View(ogrenci);
        }

        // POST: Ogrenci/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OgrenciId,Adi,SoyAdi,Email,Sifre,Token,BolumId")] Ogrenci ogrenci)
        {
            if (id != ogrenci.OgrenciId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ogrenci);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OgrenciExists(ogrenci.OgrenciId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["BolumId"] = new SelectList(_context.Bolumler, "BolumId", "BolumId", ogrenci.BolumId);
            return View(ogrenci);
        }

        // GET: Ogrenci/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var ogrenci = await _context.Ogrenciler
                .Include(o => o.Bolum)
                .FirstOrDefaultAsync(m => m.OgrenciId == id);
            if (ogrenci == null)
            {
                return NotFound();
            }

            return View(ogrenci);
        }

        // POST: Ogrenci/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var ogrenci = await _context.Ogrenciler.FindAsync(id);
            _context.Ogrenciler.Remove(ogrenci);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OgrenciExists(int id)
        {
            return _context.Ogrenciler.Any(e => e.OgrenciId == id);
        }
    }
}

OgrenciMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OgrenciMvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OgrenciMvc</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - OgrenciMvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OgrenciMvc/Views/Shared/_LayoutOgr.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>KTÜN Öğrenci Staj Otomasyon Sistemi</title>
    <link rel="icon" type="image/png" href="~/ogrenci/top_ikon.png" />
    <!--@*@ViewData["Title"] eklenirse Her layout un ViewData sı eklenir*@-->

    <environment include="Development">
        <link rel="stylesheet" href="~/ogrenci/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/ogrenci/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

    <link rel="stylesheet" href="~/ogrenci/site.css" />

    <!-- Bootstrap core CSS -->
    <link href="~/ogrenci/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/ogrenci/simple-sidebar.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css">
    <!--@*<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.dataTables.min.css">*@ -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/select/1.3.1/css/select.bootstrap4.min.css">

</head>

<body>

    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">

            <div class="sidebar-header">

                <div class="user-pic">
                    <img class="img-responsive img-rounded" src="~/image/kimlikfoto.jpg"
                    alt="User picture">

                    <span> ÖĞRENCİ ADI </span>


                </div>

            </div>


            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="Ogrenciler" asp-action="Anasayfa" asp-route-id="7">Anasayfa</a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="Ogrenciler" asp-action="StajBasvurusu">Staj Başvurusu</a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="Ogrenciler" asp-action="Listele">Staj Durumu</a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="Home" asp-action="Privacy">Staj Evrak Teslimi</a>
                <a class="list-group-item list-group-item-action bg-light" asp-area="" asp-controller="Ogrenciler" asp-action="SoruCevap">Staj Soru & Cevap</a>
                <a href="#" class="list-group-item list-group-item-action bg-light">Ek Alan</a>
            </div>
        </div>
        <!-- /#sidebar-wrapper -->
        <!-- Page Content -->
        <div id="page-content-wrapper">

            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <button class="btn btn-primary" id="menu-toggle">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Öğrenci Adı
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Ogrenci" asp-action="Logout">
                                    <i class="ace-icon fa fa-power-off"></i>
                                    Çıkış
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Ek Menü</a>
                            </div>
                        </li>
                    </ul>
                </div>

            </nav>

            <div class="main">
                
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>

                <div>
                    <footer class="border-top footer text-muted">
                        <div class="container-fluid">
                            &copy; 2020 - Ktun Staj Otomasyon 
                        </div>
                    </footer>
                </div>
            </div>

        </div>
        <!-- /#page-content-wrapper -->

    </div>

    <!-- /#wrapper -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/ogrenci/jquery.min.js"></script>
    <!--@*<script src="bootstrap.bundle.min.js"></script> Dropdow çalışması için burası kapalı kalmalıdır*@-->
    <!-- Menu Toggle Script -->
    <script>$("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("toggled");
        });</script>

    <environment include="Development">
        <script src="~/ogrenci/jquery.js"></script>
        <script src="~/ogrenci/bootstrap.bundle.js"></script>
        <link rel="stylesheet" href="~/ogrenci/site.css" />
    </environment>
    <environment exclude="Development">
        <script src="jquery.min.js"
                asp-fallback-src="jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o"></script>
        <link rel="stylesheet" href="~/ogrenci/site.css" />
    </environment>
    <script src="~/ogrenci/site.js" asp-append-version="true"></script>

    <!-- @RenderSection("Scripts", required: false)-->
    <!--@*<script src="https://code.jquery.com/jquery-3.3.1.js"></script>*@-->
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/select/1.3.1/js/dataTables.select.min.js"></script>

</body>
</html>